version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - '3000:3000'
    volumes:
      - .:/app # 変更をリアルタイムでマウントできるようルートディレクトリをappへマウント。
    depends_on:
      - django

  django:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '8000:8000'
    volumes:
      - ./todo_app:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
