version: '3'
services:
  # react-nginxは本番を想定した構成のReact・Nginxの構成。使用時はreact-devを
  # コメントアウトする。Reactのソースコードをホットリロードできないので注意。 
  # ↓
  # react-nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.front
  #   ports:
  #     - '3000:80' # 3000番ポートからのアクセスを80番ポート(Nginx)に転送。
  #   depends_on:
  #     - django

  # react-devは開発時に使用する。使用時はreact-nginxをコメントアウトする。
  # Reactのソースコードをホットリロードできる。
  # ↓
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.front-dev
    ports:
      - '3000:3000'
    depends_on:
      - django

  django:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '8000:8000'
    volumes:
      - ./todo_app_v2:/app
    depends_on:
      - db

  db:
    image: postgres:bullseye
    environment:
      POSTGRES_DB: todo_app_db
      POSTGRES_USER: todo_app_user
      POSTGRES_PASSWORD: testpass1234
    ports:
      - '5432:5432'
