version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.front
      target: react-build
    ports:
      - '3001:3000'
    volumes:
      - .:/app # 変更をリアルタイムでマウントできるようルートディレクトリをappへマウント。
    depends_on:
      - django

  django:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '8000:8000'
    volumes:
      - ./todo_app_v2:/app
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.front
      target: nginx-build
    ports:
      - '3000:80'
    depends_on:
      - react
      - django

  db:
    image: postgres:bullseye
    environment:
      POSTGRES_DB: todo_app_db
      POSTGRES_USER: todo_app_user
      POSTGRES_PASSWORD: testpass1234
    ports:
      - '5432:5432'
