# Generated by Django 5.0.1 on 2024-02-17 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生成日時"
                    ),
                ),
                (
                    "update_date_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="更新日時"
                    ),
                ),
                (
                    "del_flg",
                    models.BooleanField(default=False, verbose_name="論理削除フラグ"),
                ),
                (
                    "todo",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="todo内容"
                    ),
                ),
                ("appltype", models.JSONField(default=list, verbose_name="登録種別")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザーID",
                    ),
                ),
            ],
            options={
                "verbose_name": "todo格納テーブル",
                "verbose_name_plural": "todo格納テーブル",
                "db_table": "todo",
            },
        ),
    ]
